In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [7]:
model = svm.SVC(kernel='rbf',C=30,gamma="auto")
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9333333333333333

In [8]:
from sklearn.model_selection import cross_val_score

cross_val_score(svm.SVC(kernel='linear', C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [10]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma="auto"), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
C = [1,10,20]
avg_scores = {}
for Kval in kernels:
    for Cval in C:
        cv_scores =  cross_val_score(svm.SVC(kernel=Kval, C=Cval, gamma="auto"), iris.data, iris.target, cv=5)
        avg_scores[Kval + '_' + str(Cval)] = np.average(cv_scores)
        
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'poly_1': 0.9666666666666666,
 'poly_10': 0.9666666666666666,
 'poly_20': 0.9533333333333334,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'sigmoid_1': 0.09333333333333334,
 'sigmoid_10': 0.09333333333333334,
 'sigmoid_20': 0.09333333333333334}

In [12]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma="auto"),{
                   'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
                   'C' : [1,10,20] 
}, cv= 5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00119982, 0.00259438, 0.00099931, 0.00199838, 0.00059958,
        0.00359426, 0.00059934, 0.00199924, 0.00059948, 0.00719581,
        0.00079947, 0.00179524]),
 'std_fit_time': array([7.48750784e-04, 1.62003965e-03, 3.23406696e-07, 6.64157308e-07,
        4.89551096e-04, 2.41488484e-03, 4.89356405e-04, 2.43140197e-07,
        4.89473624e-04, 6.00992811e-03, 3.99732604e-04, 3.97954917e-04]),
 'mean_score_time': array([0.00059962, 0.00079947, 0.00040359, 0.00040011, 0.00059981,
        0.00040326, 0.00059991, 0.00039959, 0.00039978, 0.00019994,
        0.00039654, 0.00019989]),
 'std_score_time': array([0.00079966, 0.00039975, 0.00049434, 0.00049004, 0.00048975,
        0.00049393, 0.00048982, 0.0004894 , 0.00048963, 0.00039988,
        0.00048568, 0.00039978]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
 

In [13]:
results = pd.DataFrame(clf.cv_results_)
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.001200  7.487508e-04         0.000600        0.000800       1   
1        0.002594  1.620040e-03         0.000799        0.000400       1   
2        0.000999  3.234067e-07         0.000404        0.000494       1   
3        0.001998  6.641573e-07         0.000400        0.000490       1   
4        0.000600  4.895511e-04         0.000600        0.000490      10   
5        0.003594  2.414885e-03         0.000403        0.000494      10   
6        0.000599  4.893564e-04         0.000600        0.000490      10   
7        0.001999  2.431402e-07         0.000400        0.000489      10   
8        0.000599  4.894736e-04         0.000400        0.000490      20   
9        0.007196  6.009928e-03         0.000200        0.000400      20   
10       0.000799  3.997326e-04         0.000397        0.000486      20   
11       0.001795  3.979549e-04         0.000200        0.000400      20   

   param_kernel                          params  split0_test_score  \
0        linear    {'C': 1, 'kernel': 'linear'}           0.966667   
1          poly      {'C': 1, 'kernel': 'poly'}           1.000000   
2           rbf       {'C': 1, 'kernel': 'rbf'}           0.966667   
3       sigmoid   {'C': 1, 'kernel': 'sigmoid'}           0.333333   
4        linear   {'C': 10, 'kernel': 'linear'}           1.000000   
5          poly     {'C': 10, 'kernel': 'poly'}           1.000000   
6           rbf      {'C': 10, 'kernel': 'rbf'}           0.966667   
7       sigmoid  {'C': 10, 'kernel': 'sigmoid'}           0.333333   
8        linear   {'C': 20, 'kernel': 'linear'}           1.000000   
9          poly     {'C': 20, 'kernel': 'poly'}           0.966667   
10          rbf      {'C': 20, 'kernel': 'rbf'}           0.966667   
11      sigmoid  {'C': 20, 'kernel': 'sigmoid'}           0.333333   

    split1_test_score  split2_test_score  split3_test_score  \
0            1.000000           0.966667           0.966667   
1            1.000000           0.900000           0.933333   
2            1.000000           0.966667           0.966667   
3            0.100000           0.000000           0.033333   
4            1.000000           0.900000           0.966667   
5            1.000000           0.900000           0.933333   
6            1.000000           0.966667           0.966667   
7            0.100000           0.000000           0.033333   
8            1.000000           0.900000           0.933333   
9            0.966667           0.900000           0.933333   
10           1.000000           0.900000           0.966667   
11           0.100000           0.000000           0.033333   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 1.0         0.980000        0.016330                1  
1                 1.0         0.966667        0.042164                6  
2                 1.0         0.980000        0.016330                1  
3                 0.0         0.093333        0.125433               10  
4                 1.0         0.973333        0.038873                4  
5                 1.0         0.966667        0.042164                6  
6                 1.0         0.980000        0.016330                1  
7                 0.0         0.093333        0.125433               10  
8                 1.0         0.966667        0.042164                6  
9                 1.0         0.953333        0.033993                9  
10                1.0         0.966667        0.036515                5  
11                0.0         0.093333        0.125433               10

In [14]:
results["mean_test_score"] = results["mean_test_score"]*100
results["mean_test_score"]

0     98.000000
1     96.666667
2     98.000000
3      9.333333
4     97.333333
5     96.666667
6     98.000000
7      9.333333
8     96.666667
9     95.333333
10    96.666667
11     9.333333
Name: mean_test_score, dtype: float64

In [15]:
results[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0        1       linear        98.000000
1        1         poly        96.666667
2        1          rbf        98.000000
3        1      sigmoid         9.333333
4       10       linear        97.333333
5       10         poly        96.666667
6       10          rbf        98.000000
7       10      sigmoid         9.333333
8       20       linear        96.666667
9       20         poly        95.333333
10      20          rbf        96.666667
11      20      sigmoid         9.333333

In [16]:
clf.best_score_

0.9800000000000001

In [17]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

# Randomized Search CV

In [18]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(svm.SVC(gamma="auto"),{
                   'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
                   'C' : [1,10,20] 
}, cv= 5, return_train_score=False, n_iter=2)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      20      sigmoid         0.093333

In [19]:
rs.best_score_

0.9666666666666666

In [20]:
rs.best_params_

{'kernel': 'linear', 'C': 20}

# Hyper Parameter Tunning

In [21]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [22]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}