In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

# Logistic Regression

In [3]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

# SVM

In [4]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3814814814814815

# Random Forest 

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9611111111111111

# K Fold Cross Validation

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Make a function to use KFold for our digits example

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [11]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [12]:
scores_rf

[0.9198664440734557, 0.9482470784641068, 0.9348914858096828]

# cross_val_score function

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [15]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92487479, 0.95158598, 0.93489149])

# cross_val_score uses stratifield kfold by default & Parameter tunning using k fold cross validation

In [17]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8731284916201117

In [18]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9332216014897579

In [19]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9365456238361267

In [20]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9454593420235877

In [21]:
# Here we used cross_val_score to fine tune our random forest classifier and figured that /
# having around 40 trees in random forest gives best result.

# Exercise

In [22]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [23]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [24]:
x = iris.data
Y = iris.target

In [25]:
x_train, x_test, Y_train, Y_test = train_test_split(x,Y,test_size=0.2)

In [26]:
lr_model = LogisticRegression(penalty='l2',solver='newton-cg',multi_class='ovr')
lr_model.fit(x_train, Y_train)
lr_model.score(x_test, Y_test)

0.9666666666666667

In [27]:
svm = SVC(kernel='poly',gamma='scale',cache_size=500)
svm.fit(x_train, Y_train)
svm.score(x_test, Y_test)

1.0

In [28]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train, Y_train)
rf.score(x_test, Y_test)

0.9666666666666667

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [31]:
cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.96])

In [33]:
cross_val_score(DecisionTreeClassifier(criterion='entropy',splitter='random'), iris.data, iris.target, cv=3)

array([0.96, 0.92, 0.96])

# cross_val_score uses stratifield kfold by default & Parameter tunning using k fold cross validation

In [34]:
scores_lr = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target, cv=10)
np.average(scores_lr)

0.9533333333333334

In [35]:
scores_svc = cross_val_score(SVC(gamma='auto'), iris.data, iris.target, cv=10)
np.average(scores_svc)

0.9800000000000001

In [36]:
scores_rfc = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=10)
np.average(scores_rfc)

0.9666666666666666

In [37]:
scores_dtc = cross_val_score(DecisionTreeClassifier(criterion='entropy',splitter='random'), iris.data, iris.target, cv=10)
np.average(scores_dtc)

0.9400000000000001